CREATE DATABASE FOOD_DELIVERY;
USE FOOD_DELIVERY;
CREATE TABLE  CUSTOMERS (
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(30),
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE VARCHAR(10) UNIQUE NOT NULL,
    PASSWORD VARCHAR(6) NOT NULL,
    GENDER VARCHAR(10),
    DATE_OF_BIRTH DATE,
    CITY VARCHAR(50),
    STATE VARCHAR(10),
    PINCODE VARCHAR(10),
    ADDRESS VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(20) DEFAULT 'Active'
);

DESCRIBE CUSTOMERS;
-- CREATE DATABASE FOR RESTARUANTS
CREATE TABLE RESTAURANTS (
    RESTAURANT_ID INT AUTO_INCREMENT PRIMARY KEY,
    RESTAURANT_NAME VARCHAR(15) NOT NULL,
    OWNER_NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(10) UNIQUE,
    PHONE VARCHAR(15) UNIQUE,
    CITY VARCHAR(10),
    ADDRESS VARCHAR(25),
    OPENING_TIME TIME,
    CLOSING_TIME TIME,
    RATING DECIMAL(2,1) DEFAULT 0.0,
    GST_NUMBER VARCHAR(10) UNIQUE,
    STATUS VARCHAR(10) DEFAULT 'Open',
    CHECK (RATING BETWEEN 0 AND 5)
);

DESCRIBE RESTAURANTS;
CREATE TABLE  CATEGORIES (
    CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(10) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(100)
);

DESCRIBE CATEGORIES;
CREATE TABLE  MENU (
    MENU_ID INT AUTO_INCREMENT PRIMARY KEY,
    RESTAURANT_ID INT NOT NULL,
    CATEGORY_ID INT NOT NULL,
    ITEM_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRICE DECIMAL(10,2) NOT NULL,
    IS_VEG BOOLEAN DEFAULT TRUE,
    PREPARATION_TIME INT,
    AVAILABILITY BOOLEAN DEFAULT TRUE,

    CHECK (PRICE > 0),
    CHECK (PREPARATION_TIME > 0),

    FOREIGN KEY (RESTAURANT_ID)
        REFERENCES RESTAURANTS(RESTAURANT_ID),

    FOREIGN KEY (CATEGORY_ID)
        REFERENCES CATEGORIES(CATEGORY_ID)
);

DESCRIBE MENU;

CREATE TABLE  DELIVERY_PARTNERS (
    PARTNER_ID INT AUTO_INCREMENT PRIMARY KEY,
    PARTNER_NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(15) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    VEHICLE_NUMBER VARCHAR(30) UNIQUE,
    VEHICLE_TYPE VARCHAR(30),
    LICENSE_NUMBER VARCHAR(50) UNIQUE,
    JOINING_DATE DATE,
    CITY VARCHAR(50),
    STATUS VARCHAR(20) DEFAULT 'Available'
);

DESCRIBE DELIVERY_PARTNERS;
DROP TABLE ORDERS;
CREATE TABLE ORDERS (
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    RESTAURANT_ID INT NOT NULL,
    DELIVERY_PARTNER_ID INT,
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
    DELIVERY_CHARGE DECIMAL(10,2) DEFAULT 0,
    DISCOUNT DECIMAL(10,2) DEFAULT 0,
    TAX DECIMAL(10,2) DEFAULT 0,
    FINAL_AMOUNT DECIMAL(10,2) NOT NULL,
    ORDER_STATUS VARCHAR(30) DEFAULT 'Pending',
    PAYMENT_STATUS VARCHAR(20) DEFAULT 'Pending',

    CHECK (TOTAL_AMOUNT >= 0),
    CHECK (DELIVERY_CHARGE >= 0),
    CHECK (DISCOUNT >= 0),
    CHECK (TAX >= 0),
    CHECK (FINAL_AMOUNT >= 0),

    FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID),

    FOREIGN KEY (RESTAURANT_ID)
        REFERENCES RESTAURANTS(RESTAURANT_ID),

    FOREIGN KEY (DELIVERY_PARTNER_ID)
        REFERENCES DELIVERY_PARTNERS(PARTNER_ID)
);

DESCRIBE ORDERS;
CREATE TABLE  PAYMENTS (
    PAYMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    PAYMENT_METHOD VARCHAR(30) NOT NULL,
    PAYMENT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TRANSACTION_ID VARCHAR(100) UNIQUE,
    AMOUNT DECIMAL(10,2) NOT NULL,
    PAYMENT_STATUS VARCHAR(20) DEFAULT 'Pending',

    CHECK (AMOUNT > 0),

    FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID)
);

DESCRIBE PAYMENTS;
CREATE TABLE  RATINGS (
    RATING_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    RESTAURANT_ID INT NOT NULL,
    ORDER_ID INT NOT NULL,
    RATING INT NOT NULL,
    REVIEW VARCHAR(100),
    REVIEW_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CHECK (RATING BETWEEN 1 AND 5),

    FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID),

    FOREIGN KEY (RESTAURANT_ID)
        REFERENCES RESTAURANTS(RESTAURANT_ID),

    FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID)
);
DESCRIBE RATINGS;
