CREATE DATABASE tips_analysis;

use tips_analysis;

select * from  tips;
desc tips;

-- change SEX column name as GENDER
ALTER TABLE TIPS RENAME COLUMN SEX TO GENDER;
SELECT * FROM TIPS;
-- 1.GET FEMALE RECORDS
-- 2.FIND MALE RECORDS
-- 3. FIND DINNER TIEM FEMALE RECORDS
-- 4. FIND THE SIZE 2 RECORDS 
-- 5. FIND MALE SMOKER RECORDS
-- 6. GET THE NON-SMOKER FEMALE RECORDS
-- 7. GET THE DINNER TIME MALE RECORDS
-- 8. GET THE FEMALE RECORDS IN DESCENDIG ORDER AS PER TOTAL_BILLS
-- 9. GET THE TOP 5 MALE TOTAL_BILLS
-- 10. GET BOTH SIZE 2 AND 3 RECORDS
-- 11. GET THE RECORDS WHOSE TOTAL BILL IN THE REANGE OF 10 TO 20
-- 12. GET  SIZE 2,3 AND 4 RECORDS
SELECT 4 % 1;
-- 1.GET FEMALE RECORDS
SELECT *
FROM tips
WHERE GENDER = 'Female';
-- FIND MALE RECORDS
SELECT *
FROM tips
WHERE GENDER = 'Male';
-- FIND DINNER TIEM FEMALE RECORDS
SELECT * FROM tips
WHERE time = 'Dinner'
AND sex = 'Female';
-- FIND THE SIZE 2 RECORDS 
SELECT * FROM tips
WHERE SIZE = 2;
-- FIND MALE SMOKER RECORDS
SELECT * FROM tips
WHERE GENDER = 'MALE'
AND SMOKER = 'YES';
-- 6. GET THE NON-SMOKER FEMALE RECORDS
SELECT * FROM tips
WHERE GENDER = 'Female'
AND smoker = 'No';
-- GET THE DINNER TIME MALE RECORDS
SELECT * FROM tips
WHERE time = 'Dinner'
AND GENDER = 'Male';
-- GET THE FEMALE RECORDS IN DESCENDIG ORDER AS PER TOTAL_BILLS
SELECT * FROM tips
WHERE GENDER = 'Female'
ORDER BY total_bill DESC;
-- 9. GET THE TOP 5 MALE TOTAL_BILLS
SELECT * FROM tips
WHERE GENDER = 'MALE'
ORDER BY total_bill DESC
LIMIT  5;
-- GET BOTH SIZE 2 AND 3 RECORDS
SELECT * FROM tips
WHERE size = 2 OR size= 3;
-- GET THE RECORDS WHOSE TOTAL BILL IN THE REANGE OF 10 TO 20
SELECT * FROM tips
WHERE total_bill BETWEEN 10 AND 20;
-- GET  SIZE 2,3 AND 4 RECORDS
SELECT * FROM tips
WHERE size in (2,3,4);
SELECT * FROM tips
WHERE total_bill >= 10 AND total_bill >= 20;
SELECT * FROM tips
WHERE size = 2 OR SIZE = 3 OR SIZE = 4;
-- SECOND HIGHEST TOTAL BILL RECORD
SELECT * FROM TIPS
ORDER BY TOTAL_BILL DESC
LIMIT 1 OFFSET 1;

-- RETURN TOTAL RECORDS IN TIPS TABLE
SELECT COUNT(*) FROM TIPS;

-- RETURN TOTAL MALE SMOKER COUNT
SELECT COUNT(*) FROM TIPS
WHERE GENDER = 'MALE' AND SMOKER = 'YES';
-- RETURN TOTAL TIP
SELECT SUM(TIP) FROM TIPS;
-- RETURN FEMALE NON SMOKE COUNT
SELECT COUNT(*) FROM TIPS
WHERE GENDER = 'FEMALE' AND SMOKER = 'NO';
-- RETURN MINIMUM AND MAXIMIUM TOTAL BILL
SELECT GENDER, SMOKER, COUNT(*) FROM TIPS
WHERE GENDER = 'FEMALE' AND SMOKER = 'NO';



use tips_analysis;
-- GROUP BY QUERIES
-- 19. GET THE GENDER COLUMN UNIQUE VALUES
SELECT DISTINCT GENDER
FROM TIPS;
-- 20. GET THE DINNER TIME RECORDS COUNT AS PER THE GENDER COLUMN
SELECT GENDER, COUNT(*) AS DINNER_COUNT
FROM TIPS
WHERE TIME = 'Dinner'
GROUP BY GENDER;
-- 21. GET THE TOTAL RECORDS COUNT AS PER THE GENDER 
SELECT GENDER, COUNT(*) AS TOTAL_COUNT
FROM TIPS
GROUP BY GENDER;
-- 22. GET THE SMOKER AND NON-SMOKER COUNT
SELECT SMOKER, COUNT(*) AS TOTAL_COUNT
FROM TIPS
GROUP BY SMOKER;
-- 23. GET THE SUNDAY TOTAL RECORDS AS PER THE GENDER
SELECT DAY, GENDER, COUNT(*) AS TOTAL_COUNT
FROM TIPS
WHERE DAY = 'SUN'
GROUP BY GENDER;
-- 24. GET THE SIZE 2'S TOTAL COUNT AS PER THE GENDER
SELECT SIZE,GENDER, COUNT(*) AS TOTAL_COUNT
FROM TIPS
WHERE SIZE = 2
GROUP BY GENDER;
-- 25. GET THE EACH SIZE COUNT IN DESCENDING ORDER
SELECT SIZE, COUNT(*) AS TOTAL_COUNT FROM TIPS
GROUP BY SIZE
ORDER BY TOTAL_COUNT DESC;
-- 26.GET THE SIZE 2,3 AND 4 SMOKER AND NON-SMOKER count
SELECT SMOKER, COUNT(*) AS TOTAL_COUNT
FROM TIPS
WHERE SIZE IN(2,3,4)
GROUP BY SMOKER;
-- 27. GET THE EACH SIZE COUNT AS PER THE GENDER
SELECT SIZE,GENDER, COUNT(*) AS TOTAL_COUNT
FROM TIPS
GROUP BY SIZE,GENDER
ORDER BY SIZE ASC, TOTAL_COUNT DESC;

-- 28. FIND THE EACH SIZE MAXIMUM AND MINUMUM TOTAL_BILL
SELECT SIZE,MIN(TOTAL_BILL),MAX(TOTAL_BILL)  FROM TIPS
GROUP BY SIZE;
-- 29. FIND THE MALE TOTAL RECORDS AS PERTHE DAY IN DESCENDING ORDER
SELECT DAY,GENDER,COUNT(*)AS TOTAL_COUNT FROM TIPS
WHERE GENDER ='MALE'
GROUP BY DAY
ORDER BY TOTAL_COUNT DESC;

-- 30. FIND THE TOTAL ECORDS AS PER THE SIZE
SELECT SIZE,COUNT(*) AS TOTAL_COUNT FROM TIPS
GROUP BY SIZE;

-- RETURN THE SIZE WHICH ONE TOTAL COUNT IS MORETHAN 30
SELECT SIZE,COUNT(*) AS TOTAL_COUNT FROM TIPS
GROUP BY SIZE
HAVING COUNT(*) > 30;

-- GET THE EACH SIZE GENDER COUNT WHICH IS MORETHAN 20
SELECT SIZE,GENDER,COUNT(*) AS TOTAL_COUNT FROM TIPS
GROUP BY SIZE,GENDER
HAVING COUNT(*) > 20;
-- GET THE SIZES WHICH IS MAXIMUM TOTAL_BILL AND MINIMUM TOTAL_BILL DIFFERENCE IS LESSTHAN 10
SELECT SIZE,MAX(TOTAL_BILL),MIN(TOTAL_BILL),
			MAX(TOTAL_BILL) - MIN(TOTAL_BILL)  FROM TIPS
GROUP BY SIZE
HAVING MAX(TOTAL_BILL) - MIN(TOTAL_BILL) < 30;